# Configuration schema for the PowerTagging module.

powertagging.powertagging.*:
  type: config_entity
  label: 'PowerTagging'
  mapping:
    title:
      type: label
      label: 'Title'
    id:
      type: string
      label: 'ID'
    connection_id:
      type: string
      label: 'Connection ID'
    project_id:
      type: string
      label: 'Project ID'
    config:
      type: undefined
      label: 'Additional configuration'
